-- Safe migration to adjust profiles policies and clean redundant constraints
-- 1) Profiles: drop possible foreign key and open SELECT policy to everyone
ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_user_id_fkey;

-- Replace SELECT policy with an explicit public-readable policy
DROP POLICY IF EXISTS "Profiles are viewable by authenticated users" ON public.profiles;
CREATE POLICY "Profiles are viewable by everyone"
ON public.profiles
FOR SELECT
USING (true);

-- 2) RSS Feeds: drop potential redundant unique constraint name generated by earlier migrations
ALTER TABLE public.rss_feeds DROP CONSTRAINT IF EXISTS rss_feeds_url_key;

-- Keep the explicit unique constraint added previously
-- (If it does not exist yet, create it safely)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint c
    JOIN pg_class t ON c.conrelid = t.oid
    WHERE t.relname = 'rss_feeds' AND c.conname = 'rss_feeds_url_unique'
  ) THEN
    ALTER TABLE public.rss_feeds ADD CONSTRAINT rss_feeds_url_unique UNIQUE (url);
  END IF;
END $$;