// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://adllopjxodsyglyctqdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFkbGxvcGp4b2RzeWdseWN0cWR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNDQwNjUsImV4cCI6MjA3NDkyMDA2NX0.heHpAicqiLJlZBMWJYgWjUtvPAch_Rs9jWXy8tT0wvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'X-Client-Info': 'itl-brasil-portal',
    },
  },
});

// Auth state monitoring é gerenciado exclusivamente pelo SecureAuthContext
// para evitar race conditions e duplicação de lógica